In [ ]:
import pandas as pd
import numpy as np

# **Carga y limpieza de dataset de Recetas**

In [ ]:
recetas = pd.read_csv("/content/recetas.csv", sep="|", index_col="Id")
recetas.drop(["Valoracion", "Num_comentarios","Num_reviews","Fecha_modificacion", "Tipo", "Ingredientes"], axis=1, inplace=True)
recetas = recetas.convert_dtypes()

seleccion = [58251, 66067, 58973, 57328, 52312, 61558, 72227, 57460, 61994, 63488, 74177, 74047, 74071, 73067, 69177, 27593, 17446, 11350, 73908, 73414, 38301, 
             71779, 57618, 58397, 65165, 74058, 26030, 74102, 74042, 61158, 73467, 67278, 73904, 64313, 12973, 74122, 74021, 60235, 55526, 51668, 74189, 73993, 
             73564, 60482, 11994, 51095, 17249, 6504, 51503, 57505, 10164, 59940, 62103, 60589, 58520, 65428, 52234, 55988, 57448, 50435]

recetas_muestra = recetas.loc[seleccion]
recetas_muestra.reset_index(inplace=True)
recetas_muestra["Categoria"] = recetas_muestra["Categoria"].str.slice(11)
recetas_muestra["Nombre"] = recetas_muestra["Nombre"].str.slice(10)

print("Muestra de recetas:", recetas_muestra.shape[0], "elementos")
recetas_muestra.head()

Muestra de recetas: 60 elementos

,Id,Categoria,Nombre,Dificultad,Num_comensales,Tiempo,Link_receta
0,58251,Aperitivos y tapas,"Sándwich de pollo, bacon y huevo",baja,1,30m,https://www.recetasgratis.net/receta-de-sandwi...
1,66067,Aperitivos y tapas,Bocadillo de jamón serrano y queso con tomate,baja,2,30m,https://www.recetasgratis.net/receta-de-bocadi...
2,58973,Aperitivos y tapas,Sándwich de aguacate y atún,baja,1,10m,https://www.recetasgratis.net/receta-de-sandwi...
3,57328,Aperitivos y tapas,Empanadas de chorizo y queso,media,8,1h 30m,https://www.recetasgratis.net/receta-de-empana...
4,52312,Aperitivos y tapas,Empanadillas de atún y huevo,media,6,30m,https://www.recetasgratis.net/receta-de-empana...

In [ ]:
recetas = pd.read_csv("/content/recetas.csv", sep="|")
recetas.drop(["Valoracion", "Num_comentarios","Num_reviews","Fecha_modificacion", "Tipo", "Ingredientes"], axis=1, inplace=True)
recetas = recetas.convert_dtypes()

seleccion = [58251, 66067, 58973, 57328, 52312, 61558, 72227, 57460, 61994, 63488, 74177, 74047, 74071, 73067, 69177, 27593, 17446, 11350, 73908, 73414, 38301, 
             71779, 57618, 58397, 65165, 74058, 26030, 74102, 74042, 61158, 73467, 67278, 73904, 64313, 12973, 74122, 74021, 60235, 55526, 51668, 74189, 73993, 
             73564, 60482, 11994, 51095, 17249, 6504, 51503, 57505, 10164, 59940, 62103, 60589, 58520, 65428, 52234, 55988, 57448, 50435]

recetas["Categoria"] = recetas["Categoria"].str.slice(11)
recetas["Nombre"] = recetas["Nombre"].str.slice(10)

print("Muestra de recetas:", recetas.shape[0], "elementos")
recetas.head()

Muestra de recetas: 22374 elementos
Muestra de recetas: 22374 elementos

,Id,Categoria,Nombre,Dificultad,Num_comensales,Tiempo,Link_receta
0,74138,Aperitivos y tapas,Baleadas hondureñas,baja,2,10m,https://www.recetasgratis.net/receta-de-balead...
1,74133,Aperitivos y tapas,Tacos de carne molida,baja,4,30m,https://www.recetasgratis.net/receta-de-tacos-...
2,74154,Aperitivos y tapas,Burritos norteños,muy baja,5,30m,https://www.recetasgratis.net/receta-de-burrit...
3,74146,Aperitivos y tapas,Croquetas de pollo caseras de la abuela,baja,4,45m,https://www.recetasgratis.net/receta-de-croque...
4,74081,Aperitivos y tapas,Masa para empanadas fritas,baja,3,30m,https://www.recetasgratis.net/receta-de-masa-p...

# **Request de la url de dbpedia y conversión de datos obtenidos**

In [ ]:
import requests

url = 'https://api.dbpedia-spotlight.org/en/annotate'
dic_ingrediente = {"Id":[], "Nombre":[],"dbpedia_Uri":[],"dbpedia_Type":[]}

x = requests.get(url, params = {"text": recetas_muestra.loc[3]["Nombre"], "confidence" : "0.5"}, 
                     headers = {"Accept": "application/json"})

print(x.text)

{"@text":"Empanadas de chorizo y queso","@confidence":"0.5","@support":"0","@types":"","@sparql":"","@policy":"whitelist","Resources":[{"@URI":"http://dbpedia.org/resource/Empanada","@support":"247","@types":"Wikidata:Q2095,DBpedia:Food","@surfaceForm":"Empanadas","@offset":"0","@similarityScore":"0.9999999999997016","@percentageOfSecondRank":"0.0"},{"@URI":"http://dbpedia.org/resource/Chorizo","@support":"385","@types":"Wikidata:Q2095,DBpedia:Food","@surfaceForm":"chorizo","@offset":"13","@similarityScore":"0.9996515968104602","@percentageOfSecondRank":"3.4852461629158093E-4"}]}

In [ ]:
for row in range(recetas_muestra.shape[0]):
    x = requests.get(url, params = {"text": recetas_muestra.loc[row]["Nombre"], "confidence" : "0.5"}, 
                     headers = {"Accept": "application/json"})
    x = x.json()
    if 'Resources' in x:
        for i in range(len(x['Resources'])):
            dic_ingrediente["Id"].append(recetas_muestra.loc[row]["Id"])
            dic_ingrediente["Nombre"].append(x['Resources'][i]['@surfaceForm'])
            dic_ingrediente["dbpedia_Uri"].append(x['Resources'][i]['@URI'])
            dic_ingrediente["dbpedia_Type"].append(x['Resources'][i]['@types'])

In [ ]:
print(dic_ingrediente.get("Nombre"))
print()
print("Tamaño del diccionario:", len(dic_ingrediente["Nombre"]))
print()
print("Uris de primeros ingredientes:\n", dic_ingrediente.get("dbpedia_Uri")[0:3])

['jamón serrano', 'aguacate', 'Empanadas', 'chorizo', 'Risotto', 'nueces', 'Risotto', 'Paella', 'limón', 'dulce de leche', 'chocolate', 'Salpicón', 'ajo', 'curry', 'tocino', 'salsa', 'Bacalao', 'Bacalao', 'Bacalao', 'calabaza', 'calamares', 'cerdo', 'nueces', 'calabaza', 'calabaza', 'chorizo', 'calabaza', 'horno', 'pavo', 'salsa', 'pavo', 'salsa', 'salsa', 'cerdo', 'salsa', 'Ensalada', 'nueces', 'Ensalada', 'Ensalada', 'Ensalada', 'pepino', 'Refrescante', 'Ensalada', 'norteños', 'la abuela', 'Hummus', 'Ceviche', 'mango', 'Edamame', 'croquetas', 'Farofa', 'Muhammara', 'boletus', 'Ceviche', 'pota', 'Navidad', 'Nueces', 'Quesadillas', 'flor', 'calabaza', 'Ceviche', 'Ceviche', 'Sarmale', 'Quiche', 'Quiche', 'Ceviche', 'Ceviche', 'Ceviche', 'cochayuyo', 'Arepas', 'Ceviche', 'tartas', 'Ceviche', 'Jamaica', 'Chimichanga', 'horno', 'Arepas', 'Ceviche', 'horno', 'Quiche Lorraine', 'Fiambre', 'Strudel', 'horno', 'Empanada', 'hojaldre', 'Fajitas', 'palmitos', 'Hallacas', 'pionono', 'horno', 'queso blanco', 'Quiche', 'sin', 'gluten', 'Empanada', 'Ceviche', 'mejillones', 'Quiche', 'Tempeh', 'pisto', 'relleno', 'relleno', 'cabra', 'Fajitas', 'tofu', 'Quiche', 'cabra', 'Empanadas', 'Empanada', 'bacalao', 'Empanada', 'Fajitas', 'Flores', 'horno', 'Crema', 'relleno', 'horno', 'Quiche', 'humita', 'Quiche', 'harina', 'avena', 'pasta', 'filo', 'Rollo', 'albahaca', 'pasta', 'filo', 'Crema', 'calabaza', 'cacao', 'nata', 'Antipasto', 'Crema', 'sin', 'Antipasto', 'canelones', 'Empanada', 'Empanadas', 'Empanada', 'picada', 'curry', 'Mini', 'horno', 'Quiche', 'serranito', 'avena', 'Arepas', 'Hummus', 'pimiento', 'asado', 'Hummus', 'menta', 'Quesadillas', 'pavo', 'Quiche', 'Quiche', 'tofu', 'hummus', 'relleno', 'frankfurt', 'tofu', 'ajo', 'jamón serrano', 'jamón serrano', 'tempeh', 'horno', 'hojaldre', 'curry', 'quinoa', 'Quiche', 'puchero', 'Empanada', 'ajo', 'cabra', 'Hummus', 'Tostadas', 'aguacate', 'pavo', 'horno', 'Guacamole', 'granada', 'hojaldre', 'horno', 'Hummus', 'Thermomix', 'Quiche', 'cabra', 'pasas', 'pavo', 'Empanada', 'Fajitas', 'picada', 'Garam Masala', 'la India', 'cabra', 'Arepas', 'horno', 'Empanada', 'tofu', 'soja', 'vieiras', 'Empanada', 'jamón serrano', 'Guacamole', 'Quiche', 'nueces', 'integral', 'Ceviche', 'camarón', 'palta', 'Fajitas', 'salsa verde', 'jamón serrano', 'pimiento', 'hojaldre', 'mixto', 'horno', 'Veracruz', 'Hummus', 'curry', 'Oreo', 'chocolate', 'plancha', 'Empanadas', 'Sopes', 'chorizo', 'nueces', 'harina', 'Quiche', 'pavo', 'hojaldre', 'limón', 'Empanada', 'nata', 'Sandwich', 'tempeh', 'pepino', 'Quesadillas', 'horno', 'cheddar', 'jamón serrano', 'manchego', 'morcilla', 'plátano', 'macho', 'hojaldre', 'soja', 'albahaca', 'salsa', 'nata', 'Fajitas', 'Ceviche', 'Quiche', 'picada', 'Ceviche', 'Ceviche', 'cocidos', 'Nachos', 'caseros', 'Empanada', 'pisto', 'tofu', 'plátano', 'Buñuelos', 'cabra', 'Quiche', 'Quiche', 'mayonesa', 'hojaldre', 'Cachapa', 'guayaba', 'frijoles negros', 'Kebab', 'Quesadillas', 'Quiche', 'pavo', 'Quiche', 'Fajitas', 'Quiche', 'queso fundido', 'Tostadas', 'queso panela', 'Kebab', 'chile poblano', 'Fajitas', 'Arepas', 'mayonesa', 'Arepa', 'Arepa', 'sin', 'harina', 'plátano', 'horno', 'Quesadillas', 'lata', 'Quesadillas', 'huitlacoche', 'flor', 'calabaza', 'Ceviche', 'soya', 'Guacamole', 'al pastor', 'carne asada', 'aguacate', 'Quiche', 'Hojaldres', 'jamón serrano', 'horno', 'molde', 'horno', 'Quiche', 'morcilla', 'mozzarella', 'Empanadas', 'yuca', 'Empanadas', 'jamón serrano', 'Empanadas', 'Arepas', 'chía', 'Arepas', 'barbacoa', 'plátano', 'Empanada', 'bacalao', 'pasas', 'piñones', 'calamares', 'alioli', 'ajo', 'Ensenada', 'suadero', 'Fajitas', 'picada', 'plancha', 'Torta ahogada', 'Jalisco', 'Entomatadas', 'horno', 'chilaquiles', 'escalivada', 'Arepas', 'avena', 'Arepas', 'plátano', 'sin', 'harina', 'Quesadillas', 'longaniza', 'barbacoa', 'Arepas', 'plátano', 'sin', 'harina', 'pavo', 'Arepa', 'sin', 'harina', 'Arepas', 'Arepas', 'Arepas', 'Arepas', 'avena', 'Arepas', 'avena', 'harina', 'Arepas', 'cilantro', 'Sopes', 'Guadalajara', 'Quesadillas', 'Arepas', 'Arepa', 'sin', 'harina', 'Arepa', 'avena', 'Tacos al pastor', 'brie', 'Tlacoyo', 'Tostadas', 'salsa', 'aguacate', 'chile poblano', 'cerdo', 'horno', 'Soufflé', 'de 4', 'horno', 'ajo', 'Hidalgo', 'Tostadas', 'surimi', 'camarón', 'salsa', 'Empanadas', 'chorizo', 'Ceviche', 'surimi', 'mango', 'curry', 'Arepas', 'Empanadas', 'verdura', 'hojaldre', 'Crepe', 'chorizo', 'horno', 'Sorullos', 'relleno', 'picada', 'Guacamole', 'Philadelphia', 'Empanadas', 'camarón', 'salsa verde', 'surimi', 'Quiche', 'cerdo', 'camarón', 'Pincho', 'cabra', 'horno', 'hojaldre', 'horno', 'foie gras', 'chile poblano', 'Quesadillas', 'mayonesa', 'milanesa', 'Quiche', 'cabra', 'Chicharrón', 'Huarache', 'nopal', 'bistec', 'mayonesa', 'Quiche', 'mozzarella', 'Sopes', 'nopal', 'Philadelphia', 'plátano', 'Bolillo', 'relleno', 'Guacamole', 'cabra', 'harina', 'Pedro Ximénez', 'Tacos al pastor', 'alfalfa', 'hojaldre', 'Empanadas', 'calabaza', 'carpaccio', 'Chicharrón', 'salsa roja', 'Fajitas', 'manchego', 'Mini', 'Crudités', 'hummus', 'hummus', 'aguacate', 'cocido', 'Hummus', 'Quiche', 'sin', 'nata', 'Navidad', 'pavo', 'Ceviche', 'vapor', 'Empanadas', 'hojaldre', 'Tostadas', 'aguacate', 'Empanadas', 'Chimichanga', 'Quiche', 'miga', 'Thermomix', 'queso fresco', 'Halloween', 'sin', 'Chilaquiles', 'salsa', 'guacamole', 'Arepas', 'enchilada', 'Gorditas', 'Empanada', 'flor', 'calabaza', 'hojaldre', 'elote', 'asado', 'chipilín', 'Quiche', 'soja', 'Hummus', 'sin', 'tahini', 'tahina', 'relleno', 'salsa', 'pepino', 'aguacate', 'Hummus', 'salsa', 'soja', 'arrachera', 'camarón', 'Nachos', 'Fajitas', 'arrachera', 'Chorizo', 'Empanadas', 'horno', 'Empanadas', 'chorizo', 'mole', 'plátano', 'pavo', 'horno', 'caseros', 'horno', 'aguacate', 'avena', 'horno', 'aguacate', 'Empanadas', 'picada', 'Crema', 'Tostadas', 'Nachos', 'Flautas', 'salsa verde', 'Chilaquiles', 'Baguette', 'alambre', 'Fajitas', 'bechamel', 'horno', 'relleno', 'Tostadas', 'jamón serrano', 'Canapé', 'cabra', 'Empanadas', 'Quiche', 'bacalao', 'salsa', 'yakitori', 'Nachos', 'Doritos', 'cabra', 'pesto', 'pavo', 'Ceviche', 'camarón', 'aceitunas', 'Ceviche', 'camarón', 'mayonesa', 'molde', 'Mini', 'avena', 'hojaldre', 'brie', 'horno', 'Quesadillas', 'cheddar', 'hojaldre', 'Empanadas', 'bocadillo', 'Empanadas', 'Tostadas', 'albahaca', 'pavo', 'Hummus', 'clásico', 'horno', 'Hummus', 'calabaza', 'queso fundido', 'fresa', 'mango', 'Choripán', 'surimi', 'Empanada', 'cecina', 'cabra', 'Arepas', 'San Francisco', 'Taco salad', 'Ceviche', 'surimi', 'Profiteroles', 'pepino', 'relleno', 'Ceviche', 'Ceviche', 'chutney', 'durazno', 'Empanadas', 'Empanadas', 'Vigilia', 'cabra', 'Ceviche', 'camarón', 'tilapia', 'salsa', 'aguacate', 'plancha', 'Sushi', 'Empanada', 'Mini', 'pepperoni', 'la carbonara', 'Tostadas', 'Crema', 'Empanada', 'cocido', 'pavo', 'Empanada', 'Salsa', 'chocolate', 'plátano', 'Quiche', 'horno', 'Ceviche', 'Crema', 'pepino', 'menta', 'Empanadas', 'mole', 'camarón', 'Tapenade', 'cabra', 'entremeses', 'aguacate', 'Skordalia', 'pino', 'arrachera', 'horno', 'risotto', 'curry', 'horno', 'Arepas', 'fresco', 'Ceviche', 'aguacate', 'salsa', 'satay', 'Quiche', 'pepino', 'Navidad', 'cabra', 'Bruschetta', 'palta', 'Ceviche', 'camarón', 'Tapas', 'hojaldre', 'cerdo', 'Empanadas', 'chorizo', 'sin', 'gluten', 'cilantro', 'Quiche', 'Ensalada', 'aceitunas', 'canasta', 'Bombones', 'albóndigas', 'Arepas', 'avena', 'pimiento', 'nueces', 'Salsa', 'ajo', 'Ají', 'aguacate', 'Ceviche', 'vieiras', 'Ceviche', 'plátano', 'horno', 'Flautas', 'chorizo', 'Blinis', 'Nachos', 'polenta', 'polenta', 'Blinis', 'Blinis', 'cabra', 'Tostadas', 'Nachos', 'surimi', 'la cerveza', 'Tostadas', 'epazote', 'albahaca', 'Ceviche', 'Mini', 'Empanadas', 'bacalao', 'Hummus', 'cabrales', 'Flautas', 'molde', 'horno', 'Quiche', 'Empanadas', 'pino', 'yuca', 'Arepa', 'tilapia', 'sin', 'gluten', 'guayaba', 'Ceviche', 'bacalao', 'Fajitas', 'Empanadas', 'camarón', 'Fajitas', 'limón', 'Chilaquiles', 'palta', 'Quesadillas', 'elote', 'Crostini', 'tigre', 'Ceviche', 'tigre', 'arrachera', 'fresa', 'Ghee', 'salsa', 'chile poblano', 'salsa', 'Flautas', 'Ceviche', 'camarón', 'merluza', 'Arepas', 'Gorditas', 'Pan bagnat', 'Albóndigas', 'chutney', 'banana', 'Hummus', 'frijoles negros', 'Falafel', 'soja', 'Tacos al pastor', 'chicharrón', 'horno', 'Samosa', 'curry', 'hojaldre', 'Quesadillas', 'Empanada', 'plátano', 'hojaldre', 'aguacate', 'Fajitas', 'carnitas', 'Tostada', 'Empanada', 'Tzatziki', 'Arepas', 'cilantro', 'limón', 'Canapé', 'morcilla', 'Tostadas', 'horno', 'Sofrito', 'fajitas', 'Sopes', 'Empanadas', 'humita', 'relleno', 'Empanadas', 'americano', 'Hojaldres', 'morcilla', 'Empanadas', 'Sopes', 'americano', 'Empanada', 'Pincho', 'tortilla', 'Arepas', 'Mini', 'pasteles', 'americano', 'Empanadas', 'Empanadas', 'Tostadas', 'surimi', 'Ceviche', 'mixto', 'camarón', 'Arepa', 'aceitunas', 'aguacate', 'picada', 'Empanadas', 'Ceviche', 'mango', 'Quiche', 'Ceviche', 'Ceviche', 'lubina', 'Ceviche', 'Quiche', 'quiche', 'pecorino', 'Empanada', 'fresco', 'quinoa', 'aguacate', 'Hummus', 'chocolate', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'Canapé', 'Thermomix', 'Navidad', 'Quiche', 'Hojaldres', 'Quesadillas', 'Ceviche', 'mango', 'Hummus', 'Tostadas', 'Empanadas', 'hojaldre', 'Hummus', 'aguacate', 'picada', 'aguacate', 'Empanadas', 'sin', 'horno', 'Canapé', 'VALLE DEL CAUCA', 'integral', 'cabra', 'quinoa', 'quinoa', 'Ceviche', 'quinoa', 'camarón', 'Sinaloa', 'Budapest', 'Empanadas', 'plátano', 'ajo', 'Fajitas', 'cerdo', 'Canapé', 'gula', 'pavo', 'Arepas', 'cabrales', 'horno', 'Entremés', 'queso fresco', 'aguacate', 'Nacatamal', 'pasas', 'roquefort', 'Guacamole', 'Chipa', 'Soufflé', 'Mini', 'Empanadas', 'relleno', 'yuca', 'mejillones', 'Soufflé', 'mozzarella', 'hojaldre', 'samfaina', 'relleno', 'Halloumi', 'Bruschetta', 'Valentín', 'la cerveza', 'Empanada', 'Empanadas', 'Enchilada', 'Tapas', 'caseros', 'Pisto', 'Milanesa', 'salsa verde', 'salsa', 'plancha', 'hojaldre', 'relleno', 'Ceviche', 'PIÑONES', 'fajitas', 'Arepas', 'Ranchero', 'Tostadas', 'Fajitas', 'ricotta', 'queso fresco', 'pimiento', 'Soufflé', 'Ceviche', 'horno', 'pavo', 'Nachos', 'guacamole', 'sin', 'gluten', 'hojaldre', 'Halloween', 'Shawarma', 'Pincho', 'Empanada', 'Halloween', 'Nachos', 'albahaca', 'Quiche', 'merluza', 'Hummus', 'Crema', 'americano', 'Empanada', 'horno', 'escabeche', 'Empanada', 'picada', 'criolla', 'ajo', 'cerdo', 'salsa roja', 'Plátano', 'Empanadas', 'chorizo', 'Tostadas', 'secreto', 'Ibérico', 'albahaca', 'Empanadas', 'pavo', 'cerdo', 'chutney', 'mango', 'Ceviche', 'mejillones', 'Quesadillas', 'mozzarella', 'Empanada', 'Ceviche', 'tilapia', 'mango', 'Quiche', 'Quiche', 'hojaldre', 'hojaldre', 'Guacamole', 'el verano', 'salsa', 'Cocktail', 'Empanadas', 'morcilla', 'aguacate', 'Aceitunas', 'Pate', 'Yoghurt', 'finas', 'Tofu', 'Ceviche', 'Ceviche', 'Exótico', 'Ceviche', 'Ceviche', 'ceviche', 'Ceviche', 'Ceviche', 'Ceviche', 'Ceviche', 'Ceviche', 'Ceviche', 'Empanadas', 'ciruela', 'Empanada', 'Empanadas', 'cuatro', 'Empanadas', 'Empanadas', 'Vigilia', 'Empanadas', 'Empanadas', 'Empanadas', 'Empanadas', 'Chilorio', 'vieiras', 'Tortilla de patatas', 'horno', 'sabrosa', 'tortilla', 'tataki', 'fresco', 'Tataki', 'tempura', 'salsa', 'yoghurt', 'Morcilla', 'morcilla', 'relleno', 'boletus', 'Cabra', 'Salsa', 'pesto', 'merluza', 'tortilla', 'anchoa', 'tortilla', 'nueces', 'roquefort', 'morcilla', 'Morcilla', 'Morcilla', 'Magret', 'Magret', 'bacalao', 'salsa', 'escalivada', 'escalivada', 'Pincho', 'relleno', 'almendra', 'empanada', 'cordero', 'boquerones', 'escalivada', 'fresco', 'gorgonzola', 'albóndigas', 'salsas', 'albóndigas', 'salsa', 'Pringá', 'Pringá', 'Chorizo', 'chorizo', 'Philadelphia', 'Philadelphia', 'Bacalao', 'albahaca', 'Yakitori', 'Mitarashi Dango', 'Shawarma', 'cordero', 'Shawarma', 'Pate', 'Salsa', 'Cilantro', 'yoghurt', 'Manjar', 'Cielo', 'Jugo', 'Juanito', 'Aloja', 'Gringo', 'Vodka', 'Naranja', 'Oporto', 'Espuma', 'Corazón', 'Sopaipillas', 'Sandwich', 'Americano', 'Primavera', 'Rompon', 'Rompe', 'Princesa', 'Apricot', 'Aguardiente', 'Jerez', 'Canela', 'Caliente', 'Chirimoya', 'Cazuela', 'Pachanga', 'Negrito', 'Arepa', 'salame', 'Arepa', 'pancetta', 'Frankfurt', 'completo', 'cerdo', 'relleno', 'platano', 'bocadillo', 'Pinchitos', 'Ensalada', 'Montecarlo', 'aguardiente', 'Ceviche', 'soya', 'Bomba', 'Rollo', 'Philadelphia', 'Crema', 'Canapé', 'Salpicon', 'Canapé', 'aguacate', 'anchoa', 'Fiori', 'Cocadas', 'Provolone', 'Aceitunas', 'Salsa', 'ciboulette', 'Empanada', 'Thermomix', 'Thermomix', 'Empanada', 'Thermomix', 'aceitunas', 'Thermomix', 'Delicias', 'Elche', 'Canape', 'humita', 'picada', 'Buñuelos', 'caseros', 'Arepa', 'Ceviche', 'criollos', 'Empanadas', 'Benjamin', 'Chicharrones', 'Cerdo', 'salsa', 'Tostadas', 'polaco', 'Empanadas', 'Venezuela', 'Ceviche', 'caracol', 'pastel', 'bocadillo', 'empanada', 'Ceviche', 'jalisco', 'palta', 'Ceviche', 'salsa verde', 'Empanadas', 'pico de gallo', 'soya', 'Ceviche', 'croquetas', 'empanada', 'Cebiche', 'Ceviche', 'camarón', 'Perú', 'norteños', 'Tamaulipas', 'canape', 'salsa', 'Tostones', 'Tostadas', 'Ensenada', 'surimi', 'Camembert', 'Salbutes', 'tostadas', 'salsa', 'Quiche', 'Quiche', 'Pincho', 'brie', 'Humitas', 'albahaca', 'palta', 'Empanadas', 'Empanadas', 'salteñas', 'Empanadas', 'horno', 'Empanadas', 'horno', 'pavo', 'avena', 'la diabla', 'Ceviche', 'Ceviche', 'Cebiche', 'harina', 'Arepa', 'Quesadillas', 'horno', 'tostadas', 'siberia', 'laredo', 'Ceviche', 'soya', 'nueces', 'croquetas', 'pickles', 'Empanadas', 'Como', 'Migas', 'cilantro', 'Tijuana', 'Falafel', 'croquetas', 'Chicharron', 'Calamares', 'COLIMA', 'Thermomix', 'Empanadas', 'horno', 'escondido', 'salsa', 'picadillo', 'paiche', 'Empanadas', 'Crema', 'Ceviche', 'ají amarillo', 'salsa', 'chipotle', 'hojaldre', 'empanada', 'salmon', 'Empanadas', 'horno', 'Empanadas', 'calabaza', 'marlin', 'Empanadas', 'Migas', 'Ceviche', 'mango', 'Entomatadas', 'migas', 'Ceviche', 'camarón', 'cabra', 'ceviche', 'caracol', 'voli', 'pa amb tomàquet', 'croquetas', 'Papas fritas', 'pimenton', 'palitos', 'mofongo', 'relleno', 'queso blanco', 'migas', 'Vicente', 'la cerveza', 'Quiche Lorraine', 'pepito', 'mixto', 'Pincho', 'Bacalao', 'Pincho', 'ajo', 'Pincho', 'Pincho', 'relleno', 'anchoa', 'canapé', 'mousse', 'Pincho', 'Pincho', 'oca', 'Pincho', 'Cocktail', 'Pincho', 'Pincho', 'Urbasa', 'Pincho', 'Pincho', 'Tafalla', 'Pincho', 'relleno', 'Pincho', 'Pincho', 'Pincho', 'Pincho', 'Tolosa', 'Pincho', 'Pincho', 'queso fresco', 'Pincho', 'Ronda', 'relleno', 'Salpicón', 'Pincho', 'Amara', 'Pincho', 'rape', 'Carmencita', 'Pincho', 'Anchoa', 'compañía', 'queso fundido', 'Pincho', 'Pincho', 'Primavera', 'Pincho', 'Atari', 'Gernika', 'Sepia', 'Salpicón', 'Pincho', 'Ensalada', 'merluza', 'Pincho', 'Cazuela', 'Pincho', 'Roquefort', 'nueces', 'pisto', 'lasagna', 'Pincho', 'bacalao', 'bocadillo', 'LA VIRGINIA', 'MEJILLONES', 'PAVO', 'Empanadas', 'Sandwich', 'menorquín', 'camarón', 'Empanadas', 'Empanadas', 'empanada', 'Empanadas', 'ricotta', 'hotel', 'pimiento', 'pavo', 'calamares', 'salsa', 'Empanada', 'calabaza', 'Empanada', 'Quiche', 'integral', 'Crema', 'Canapé', 'pimiento', 'Tostadas', 'Canapé', 'cabra', 'horno', 'Canelones', 'Empanadas', 'anchoa', 'Tabbouleh', 'yuca', 'Hummus', 'hojaldre', 'Empanada', 'Adobo', 'Ceviche', 'Acapulco', 'rape', 'Salsa', 'Blanco', 'ajo', 'cerdo', 'jerez', 'marinera', 'salsa', 'Humitas', 'horno', 'Hallacas', 'Empanada', 'Empanada', 'brandy', 'Caviar', 'Arepas', 'yuca', 'Empanadas', 'aguacate', 'Flan', 'Empanadas', 'Quiche Lorraine', 'hojaldre', 'chicharrón', 'Empanada', 'Empanadas', 'Empanadas', 'Empanada', 'Empanada', 'bacalao', 'Empanada', 'bacalao', 'Empanada', 'pasas', 'Cebiche', 'Cebiche', 'Inca', 'Cebiche', 'Cebiche', 'Cebiche', 'Acapulco', 'Albóndigas', 'tuna', 'salsa', 'guacamole', 'finas', 'pavo', 'cabrales', 'orujo', 'Magret', 'salsa', 'Foie gras', 'Madeira', 'Cebiche', 'Cerdo', 'Migas', 'Migas', 'chorizo', 'Machaca', 'salsa verde', 'Empanada', 'Empanada', 'Chicharrón', 'salsa verde', 'cerdo', 'Cabrales', 'Albóndigas', 'mozzarella', 'Empanada', 'Salteñas', 'relleno', 'Empanadas', 'Empanadas', 'Cazuela', 'Enchilada', 'celaya', 'Enchilada', 'Sandwich', 'mozzarella', 'mozzarella', 'campesino', 'soja', 'caviar', 'aceitunas', 'caviar', 'mejillones', 'Armadillo', 'adobo', 'Gazpacho', 'Yeclano', 'Espuma', 'Tomate', 'Plátanos', 'Espuma', 'Espuma', 'Empanadas', 'yuca', 'cocido', 'Adobo', 'Chile', 'Pasilla', 'Ceviche', 'Ceviche', 'Ceviche', 'Lubina', 'Vieiras', 'Ceviche', 'Caliente', 'Ceviche', 'Caviar', 'Canapé', 'Tempura', 'Naranja', 'Oregano', 'Salsa', 'Oporto', 'Sevillanas', 'Pate', 'Escalivada', 'Bacalao', 'empanada', 'Piñones', 'Tomate', 'Tacos al pastor', 'soya', 'Fajitas', 'Arepa', 'Crema', 'Buñuelos', 'yuca', 'Ceviche', 'Pincho', 'salmon', 'salsa', 'Pate', 'mayonesa', 'Empanadas', 'Ceviche', 'Cebiche', 'Cebiche', 'como', 'Ceviche', 'Humitas', 'tuna', 'Ceviche', 'mango', 'pimenton', 'Tostones', 'burdeos', 'Taramasalata', 'Empanadas', 'Ceviche', 'mango', 'cerdo', 'plátano', 'pimiento', 'Quiche', 'Pincho', 'croquetas', 'Empanada', 'hojaldre', 'jamón serrano', 'cocido', 'Empanadas', 'harina', 'aguacate', 'Empanadas', 'surimi', 'aperitivo', 'Empanadas', 'Empanadas', 'cerdo', 'plancha', 'relleno', 'Buñuelos', 'yuca', 'Buñuelos', 'Ceviche', 'camarón', 'Sinaloa', 'Quiche', 'cochinita pibil', 'limÓn', 'Crema', 'relleno', 'crab', 'Antipasto', 'Tostada', 'La Siberia', 'Crema', 'aji', 'Sandwich', 'Ceviche', 'kion', 'huitlacoche', 'platano', 'Empanada', 'ourense', 'Chivito', 'relleno', 'Ceviche', 'Empanadas', 'Quiche', 'Salsa', 'migas', 'la mancha', 'calamares', 'Empanadas', 'yuca', 'roquefort', 'mozzarella', 'Sandwich', 'humita', 'aperitivo', 'Ceviche', 'pepino', 'Supplì', 'croquetas', 'aceitunas', 'pasas', 'Gorditas', 'chicharron', 'pavo', 'Bollos', 'la española', 'Entomatadas', 'elote', 'Pate', 'Rollo', 'cilantro', 'cilantro', 'Humitas', 'mejillones', 'plátano', 'cordero', 'horno', 'Hummus', 'Asado', 'gluten', 'pimiento', 'cocido', 'merluza', 'Pisto', 'Empanadas', 'Empanadas', 'verdura', 'Sandwich', 'plancha', 'Sandwich', 'cerdo', 'Sandwich', 'cerdo', 'Pate', 'brandy', 'Sandwich', 'Sandwich', 'Sandwich', 'completo', 'Empanadas', 'Empanadas', 'Empanadas', 'Empanadas', 'verdura', 'Empanadas', 'albahaca', 'Empanadas', 'Empanadas', 'emmental', 'Empanadas', 'ricotta', 'Empanadas', 'Empanadas', 'Empanadas', 'Empanadas', 'Empanadas', 'Empanadas', 'Empanadas', 'Empanadas', 'Empanada', 'Empanada', 'Arepa', 'basica', 'Cebiche', 'Ceviche', 'Cebiche', 'lata', 'Ceviche', 'Cancún', 'tostada', 'banana', 'Sandwich', 'cocido', 'Empanada', 'Thermomix', 'hojaldre', 'Thermomix', 'Crema', 'Thermomix', 'empanada', 'Thermomix', 'Quiche Lorraine', 'Thermomix', 'Thermomix', 'Quiche', 'Cebolla', 'Thermomix', 'Thermomix', 'escabeche', 'Thermomix', 'cuatro', 'Thermomix', 'salami', 'Thermomix', 'Philadelphia', 'Thermomix', 'requesón', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'chorizo', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'Pate', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'surimi', 'Thermomix', 'aceitunas', 'Thermomix', 'aguacate', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'Empanada', 'Thermomix', 'Thermomix', 'Almogrote', 'Thermomix', 'LOMO', 'ACEITUNAS', 'Quiche', 'Arepas', 'Mini', 'quiche', 'Lorraine', 'roquefort', 'Thermomix', 'Thermomix', 'surimi', 'Thermomix', 'Soufflé', 'Thermomix', 'Thermomix', 'mejillones', 'Thermomix', 'nueces', 'Thermomix', 'morcilla', 'Thermomix', 'Thermomix', 'Thermomix', 'Thermomix', 'Mojo', 'Thermomix', 'salsa', 'Ceviche', 'Ceviche', 'Empanada', 'cajeta', 'Empanadas', 'calabaza', 'Tostadas', 'Ceviche', 'camarón', 'Cielito lindo', 'Thermomix', 'Quiche', 'Thermomix', 'mejillones', 'Thermomix', 'Mini', 'Thermomix', 'Empanada', 'argentina', 'Ceviche', 'Empanadas', 'chilenas', 'Ceviche', 'Ceviche', 'camarón', 'Cazuela', 'mala

In [ ]:
ingredienteDF = pd.DataFrame(dic_ingrediente)
ingredienteDF.head()

,Id,Nombre,dbpedia_Uri,dbpedia_Type
0,66067,jamón serrano,http://dbpedia.org/resource/Jamón,"Wikidata:Q2095,DBpedia:Food"
1,58973,aguacate,http://dbpedia.org/resource/Avocado,"Wikidata:Q756,Wikidata:Q19088,DBpedia:Species,..."
2,57328,Empanadas,http://dbpedia.org/resource/Empanada,"Wikidata:Q2095,DBpedia:Food"
3,57328,chorizo,http://dbpedia.org/resource/Chorizo,"Wikidata:Q2095,DBpedia:Food"
4,72227,Risotto,http://dbpedia.org/resource/Risotto,"Wikidata:Q2095,DBpedia:Food"

## **TRATAMIENTO DE DATASET DE PRECIOS DE SUPERMERCADOS**

In [ ]:
carrefour = pd.read_csv("/content/datamarket_productos_de_supermercados_2022_11_carrefour.csv", 
                        usecols=["url","supermarket","name","price","reference_price","reference_unit", "insert_date"])

carrefour = carrefour.convert_dtypes()
carrefour = carrefour[carrefour["insert_date"]==("2022-11-17")]
carrefour.reset_index(inplace=True)
carrefour.drop(["insert_date", "index"], axis=1, inplace=True)
carrefour = carrefour.drop(carrefour[carrefour["name"].isna()].index) 

print("Entradas de productos:", carrefour.shape[0], "elementos")
carrefour.head()

Entradas de productos: 2910 elementos

,url,supermarket,name,price,reference_price,reference_unit
0,https://www.carrefour.es/supermercado/pack-de-...,carrefour-es,"Pack de 3 bombillas led dicroica 4,6W(=50W) GU...",6.25,2.08,ud
1,https://www.carrefour.es/supermercado/cinta-ai...,carrefour-es,Cinta aislante en Pvc 7000v tesa 10mx15mm,1.99,1.99,ud
2,https://www.carrefour.es/supermercado/precinto...,carrefour-es,Precinto Tesa Basic Marrón 66 m x 50 mm,2.59,2.59,ud
3,https://www.carrefour.es/supermercado/cinta-ad...,carrefour-es,Cinta Adhesiva Embalaje Polipropileno Transpar...,2.89,2.89,ud
4,https://www.carrefour.es/supermercado/cinta-am...,carrefour-es,Cinta americana universal extra power tesa 25m...,8.15,8.15,ud

In [ ]:
ingredientes_lista = list(set(ingredienteDF["Nombre"]))
carrefour_lista = list(carrefour["name"])
carrefour_seleccion = pd.DataFrame(columns=carrefour.columns)

for i in range(len(ingredientes_lista)):
  for j in range(len(carrefour_lista)):
    if ingredientes_lista[i] in carrefour_lista[j]:
        carrefour_seleccion = carrefour_seleccion.append(carrefour.loc[j])

carrefour_seleccion.head()

,url,supermarket,name,price,reference_price,reference_unit
628,https://www.carrefour.es/supermercado/wok-de-t...,carrefour-es,Wok de tallarines con pollo al curry Carrefour...,3.25,3.25,ud
1718,https://www.carrefour.es/supermercado/gazpacho...,carrefour-es,Gazpacho suave sin pepino Extra Carrefour sin ...,1.39,1.39,l
1838,https://www.carrefour.es/supermercado/lavavaji...,carrefour-es,Lavavajillas a mano aroma aloe vera y pepino F...,2.99,4.60,l
2783,https://www.carrefour.es/supermercado/lavavaji...,carrefour-es,Lavavajillas a mano power clean Carrefour Expe...,0.92,1.84,l
444,https://www.carrefour.es/supermercado/fanta-de...,carrefour-es,Fanta de limón zero azúcares añadidos lata 33 cl.,0.52,1.58,l

In [ ]:
dia = pd.read_csv("/content/datamarket_productos_de_supermercados_2022_11_dia.csv", 
                        usecols=["url","supermarket","name","price","reference_price","reference_unit", "insert_date"])
dia = dia.convert_dtypes()
dia = dia[dia["insert_date"]==("2022-11-17")]
dia.reset_index(inplace=True)
dia.drop(["insert_date", "index"], axis=1, inplace=True)

print("Entradas de productos:", dia.shape[0], "elementos")
dia.head()

Entradas de productos: 5329 elementos

,url,supermarket,name,price,reference_price,reference_unit
0,https://www.dia.es/compra-online/despensa/pan/...,dia-es,BIMBO pan de molde natural 100% bolsa 460 gr,2.59,5.63,kg
1,https://www.dia.es/compra-online/despensa/pan/...,dia-es,BIMBO pan de molde blanco sin corteza bolsa 45...,2.49,5.53,kg
2,https://www.dia.es/compra-online/despensa/pan/...,dia-es,EL MOLINO DE DIA pan de molde 100% integral si...,1.41,3.13,kg
3,https://www.dia.es/compra-online/despensa/pan/...,dia-es,PANCELIAC pan rallado SIN GLUTEN bolsa 200 gr,1.89,9.45,kg
4,https://www.dia.es/compra-online/despensa/pan/...,dia-es,ESGIR Crunchy crumbs rebozado crujiente SIN GL...,1.79,8.95,kg

In [ ]:
dia_lista = list(dia["name"])
dia_seleccion = pd.DataFrame(columns=dia.columns)

for i in range(len(ingredientes_lista)):
  for j in range(len(dia_lista)):
    if ingredientes_lista[i] in dia_lista[j]:
        dia_seleccion = dia_seleccion.append(dia.loc[j])

print("Entradas de productos:", dia_seleccion.shape[0], "elementos")
dia_seleccion.head()

Entradas de productos: 617 elementos

,url,supermarket,name,price,reference_price,reference_unit
1474,https://www.dia.es/compra-online/despensa/coci...,dia-es,MAGGI fideos fusian India curry sobre 118 gr,1.69,14.32,kg
2914,https://www.dia.es/compra-online/despensa/sal-...,dia-es,DIA VEGECAMPO curry en polvo bote 42 gr,0.85,20.24,kg
4099,https://www.dia.es/compra-online/cuidado-perso...,dia-es,DOVE desodorante go fresh pepino zero aluminio...,2.89,57.80,l
994,https://www.dia.es/compra-online/platos-prepar...,dia-es,DIA AL PUNTO tortilla de patatas fresca con ch...,3.55,5.92,kg
999,https://www.dia.es/compra-online/platos-prepar...,dia-es,DIA AL PUNTO lentejas con chorizo lata 430 gr,1.05,2.53,kg

In [ ]:
mercadona = pd.read_csv("/content/datamarket_productos_de_supermercados_2022_11_mercadona.csv",
                        usecols=["url","supermarket","name","price","reference_price","reference_unit", "insert_date"])
mercadona = mercadona.convert_dtypes()
mercadona = mercadona[mercadona["insert_date"]==("2022-11-17")]
mercadona.reset_index(inplace=True)
mercadona.drop(["insert_date", "index"], axis=1, inplace=True)

print("Entradas de productos:", mercadona.shape[0], "elementos")
mercadona.head()

Entradas de productos: 5371 elementos

,url,supermarket,name,price,reference_price,reference_unit
0,https://tienda.mercadona.es/product/35998/lava...,mercadona-es,Lavavajillas Ultra concentrado Bosque Verde,1.95,1.5,l
1,https://tienda.mercadona.es/product/42441/lava...,mercadona-es,Lavavajillas a mano Bosque Verde,1.2,0.924,l
2,https://tienda.mercadona.es/product/42130/lava...,mercadona-es,Lavavajillas Aloe Vera y Pepino Fairy líquido,2.45,4.712,l
3,https://tienda.mercadona.es/product/42384/lava...,mercadona-es,Lavavajillas Todo en 1 Bosque Verde en pastillas,2.85,5.589,kg
4,https://tienda.mercadona.es/product/42314/abri...,mercadona-es,Abrillantador lavavajillas líquido Bosque Verde,1.3,1.734,l

In [ ]:
mercadona_lista = list(mercadona["name"])
mercadona_seleccion = pd.DataFrame(columns=mercadona.columns)

for i in range(len(ingredientes_lista)):
  for j in range(len(mercadona_lista)):
    if ingredientes_lista[i] in mercadona_lista[j]:
        mercadona_seleccion = mercadona_seleccion.append(mercadona.loc[j])

print("Entradas de productos:", mercadona_seleccion.shape[0], "elementos")
mercadona_seleccion.head()

Entradas de productos: 511 elementos

,url,supermarket,name,price,reference_price,reference_unit
643,https://tienda.mercadona.es/product/23623/croq...,mercadona-es,Croquetas Caprichos Thai Hacendado de coliflor...,3.00,13.334,kg
1792,https://tienda.mercadona.es/product/4498/pollo...,mercadona-es,Pollo al curry Hacendado con arroz basmati,2.85,10.179,kg
3010,https://tienda.mercadona.es/product/82961/salm...,mercadona-es,Salmón al curry Hacendado,5.50,16.924,kg
3011,https://tienda.mercadona.es/product/83346/salm...,mercadona-es,Salmón al curry con arroz,3.50,12.728,kg
1809,https://tienda.mercadona.es/product/80773/tort...,mercadona-es,Tortilla de patata con chorizo Hacendado,3.20,5.334,kg

## DataFrame final con entradas en supermercados que contienen los ingredientes seleccionados en el paso anterior

In [ ]:
precios_supermercados = pd.DataFrame()
precios_supermercados = precios_supermercados.append([carrefour_seleccion, dia_seleccion, mercadona_seleccion])
precios_supermercados.reset_index(inplace=True)

resultado = pd.DataFrame()
for i in range(len(precios_supermercados)):
  if "rúcula" in list(precios_supermercados["name"])[i]:
    resultado = resultado.append(precios_supermercados.iloc[i])

print(resultado)
precios_supermercados.sort_index().head()

                                                    url   supermarket  \
2870  https://tienda.mercadona.es/product/69697/ensa...  mercadona-es

                                        name  price  reference_price  \
2870  Ensalada mezcla dúo canónigos y rúcula   1.35             13.5

     reference_unit
2870             kg

,url,supermarket,name,price,reference_price,reference_unit
9,https://www.dia.es/compra-online/despensa/pan/...,dia-es,EL MOLINO DE DIA panecillos tostados con ajo y...,1.19,7.44,kg
21,https://www.dia.es/compra-online/despensa/pan/...,dia-es,EL MOLINO DE DIA hogaza con pipas de calabaza ...,2.15,4.30,kg
36,https://www.dia.es/compra-online/despensa/pan/...,dia-es,EL MOLINO DE DIA pan rallado con ajo y perejil...,1.15,2.30,kg
52,https://www.dia.es/compra-online/despensa/diet...,dia-es,WEIDER barritas de proteínas sabor chocolate b...,3.49,33.24,kg
53,https://www.dia.es/compra-online/despensa/diet...,dia-es,JUST LOADING bebida isotónica en polvo sabor l...,3.25,108.33,kg

In [ ]:
producto = precios_supermercados[["index", "name", "reference_price", "reference_unit"]]
supermercados = precios_supermercados[["index", "url", "supermarket"]]
supermercado_carrefour = supermercados[supermercados["supermarket"]==("carrefour-es")]
supermercado_carrefour.drop(["supermarket"], axis=1, inplace=True)
supermercado_carrefour

     index                                                url
0      628  https://www.carrefour.es/supermercado/wok-de-t...
1     1718  https://www.carrefour.es/supermercado/gazpacho...
2     1838  https://www.carrefour.es/supermercado/lavavaji...
3     2783  https://www.carrefour.es/supermercado/lavavaji...
4      444  https://www.carrefour.es/supermercado/fanta-de...
..     ...                                                ...
189   1329  https://www.carrefour.es/supermercado/helado-d...
190   2299  https://www.carrefour.es/supermercado/tiras-de...
191    631  https://www.carrefour.es/supermercado/crema-de...
192    659  https://www.carrefour.es/supermercado/semillas...
193   1616  https://www.carrefour.es/supermercado/pipas-de...

[194 rows x 2 columns]

In [ ]:
url = 'https://api.dbpedia-spotlight.org/en/annotate'
dic_producto = {"Id":[], "Nombre":[],"dbpedia_Uri":[],"dbpedia_Type":[]}

for row in range(precios_supermercados.shape[0]):
    x = requests.get(url, params = {"text": precios_supermercados.loc[row]["Nombre"], "confidence" : "0.5"}, 
                     headers = {"Accept": "application/json"})
    x = x.json()
    if 'Resources' in x:
        for i in range(len(x['Resources'])):
            dic_producto["Id"].append(precios_supermercados.loc[row]["Id"])
            dic_producto["Nombre"].append(x['Resources'][i]['@surfaceForm'])
            dic_producto["dbpedia_Uri"].append(x['Resources'][i]['@URI'])
            dic_producto["dbpedia_Type"].append(x['Resources'][i]['@types'])

 .............

...............

# **NO USAR - (versión 1 - demasiado manuela, no escalable) **
Carga y limpieza de dataset de Recetas ()

In [ ]:
recetas = pd.read_csv("/content/recetas.csv", sep="|", index_col="Id")
recetas = recetas.convert_dtypes()
recetas.sort_index(inplace=True)
recetas.head()

,Categoria,Nombre,Valoracion,Dificultad,Num_comensales,Tiempo,Tipo,Link_receta,Num_comentarios,Num_reviews,Fecha_modificacion,Ingredientes
Id,,,,,,,,,,,,
1,Cócteles y bebidas,Absolut tequila,3.9,baja,1,15m,<NA>,https://www.recetasgratis.net/receta-de-absolu...,1,9,<NA>,"20 mililitros de Tequila,20 mililitros de Vodk..."
2,Recetas de Verduras,Receta de Aguacate antillano,3.7,<NA>,<NA>,<NA>,<NA>,https://www.recetasgratis.net/receta-de-aguaca...,0,7,<NA>,"½ taza de la lechera,1 taza de leche,1 caballi..."
4,Recetas de Verduras,Receta de Aguacate y menta,3.7,<NA>,<NA>,<NA>,<NA>,https://www.recetasgratis.net/receta-de-aguaca...,0,7,<NA>,"½ taza de la lechera,1 taza de leche entera,1 ..."
5,Recetas de Verduras,Receta de Aguacate y plátano,3.6,<NA>,<NA>,<NA>,<NA>,https://www.recetasgratis.net/receta-de-aguaca...,4,6,<NA>,"1 aguacate grande,1 plátano,2 cucharadas cafet..."
8,Cócteles y bebidas,Cóctel refrescante de menta,2.3,baja,1,15m,<NA>,https://www.recetasgratis.net/receta-de-coctel...,0,3,<NA>,"¾ vaso pequeño de Jarabe de menta,½ vaso peque..."

In [ ]:
recetas.drop(["Valoracion", "Num_comentarios",	"Num_reviews",	"Fecha_modificacion"], axis=1, inplace=True)
recetas['Categoria'].unique()

<StringArray>
[           'Cócteles y bebidas',           'Recetas de Verduras',
            'Recetas de Pescado', 'Recetas de Arroces y cereales',
     'Recetas de Sopas y cremas', 'Recetas de Aperitivos y tapas',
           'Recetas de Mariscos',              'Recetas de Pasta',
            'Recetas de Postres',     'Recetas de Pan y bollería',
   'Recetas de Huevos y lácteos',              'Recetas de Carne',
        'Recetas de Aves y caza',          'Recetas de Legumbres',
   'Recetas de Guisos y Potajes',          'Recetas de Ensaladas',
             'Recetas de Salsas',            'Consejos de cocina']
Length: 18, dtype: string

In [ ]:
recetas1 = recetas.drop(recetas[recetas["Categoria"]==("Cócteles y bebidas" or "Recetas de Salsas" or "Consejos de cocina")].index) 
recetas1.head()

,Categoria,Nombre,Dificultad,Num_comensales,Tiempo,Tipo,Link_receta,Ingredientes
Id,,,,,,,,
2,Recetas de Verduras,Receta de Aguacate antillano,<NA>,<NA>,<NA>,<NA>,https://www.recetasgratis.net/receta-de-aguaca...,"½ taza de la lechera,1 taza de leche,1 caballi..."
4,Recetas de Verduras,Receta de Aguacate y menta,<NA>,<NA>,<NA>,<NA>,https://www.recetasgratis.net/receta-de-aguaca...,"½ taza de la lechera,1 taza de leche entera,1 ..."
5,Recetas de Verduras,Receta de Aguacate y plátano,<NA>,<NA>,<NA>,<NA>,https://www.recetasgratis.net/receta-de-aguaca...,"1 aguacate grande,1 plátano,2 cucharadas cafet..."
26,Recetas de Pescado,Receta de Ají de atún,baja,4,45m,Entrante,https://www.recetasgratis.net/receta-de-aji-de...,"½ taza de Aceite,1 unidad de cebolla pequeña p..."
27,Recetas de Pescado,Receta de Aperitivo de atún,<NA>,<NA>,<NA>,<NA>,https://www.recetasgratis.net/receta-de-aperit...,"1 sobre de puré de patatas,1 lata de atún en a..."

In [ ]:
seleccion = [58251, 66067, 58973, 57328, 52312, 61558, 72227, 57460, 61994, 63488, 74177, 74047, 74071, 73067, 69177, 27593, 17446, 11350, 73908, 73414, 38301, 
             71779, 57618, 58397, 65165, 74058, 26030, 74102, 74042, 61158, 73467, 67278, 73904, 64313, 12973, 74122, 74021, 60235, 55526, 51668, 74189, 73993, 
             73564, 60482, 11994, 51095, 17249, 6504, 51503, 57505, 10164, 59940, 62103, 60589, 58520, 65428, 52234, 55988, 57448, 50435]
recetas_muestra = recetas.loc[seleccion]
recetas_muestra["Categoria"] = recetas_muestra["Categoria"].str.slice(11)
print("Total recetas:", len(recetas_muestra))
recetas_muestra.head()

Total recetas: 60

,Categoria,Nombre,Dificultad,Num_comensales,Tiempo,Tipo,Link_receta,Ingredientes
Id,,,,,,,,
58251,Aperitivos y tapas,"Receta de Sándwich de pollo, bacon y huevo",baja,1,30m,Plato principal,https://www.recetasgratis.net/receta-de-sandwi...,"3 rebanadas de pan de molde,1 unidad de pechug..."
66067,Aperitivos y tapas,Receta de Bocadillo de jamón serrano y queso c...,baja,2,30m,Cena,https://www.recetasgratis.net/receta-de-bocadi...,"1 barra de chapata,200 gramos de jamón serrano..."
58973,Aperitivos y tapas,Receta de Sándwich de aguacate y atún,baja,1,10m,Cena,https://www.recetasgratis.net/receta-de-sandwi...,"4 rebanadas de pan de sándwich,1 puñado de Can..."
57328,Aperitivos y tapas,Receta de Empanadas de chorizo y queso,media,8,1h 30m,<NA>,https://www.recetasgratis.net/receta-de-empana...,"Masa de empanadas,150 gramos de queso mozzarel..."
52312,Aperitivos y tapas,Receta de Empanadillas de atún y huevo,media,6,30m,Entrante,https://www.recetasgratis.net/receta-de-empana...,"1 lata de atún,1 unidad de tomate rojo,½ unida..."

In [ ]:
ingredientes=set()

lista=list(recetas_muestra["Nombre"].str.split())

final = (" ", ",", ".", "os", "as")
#palabrasVacias = ["receta", "a", "al", "con", "de", "y", "en", "estilo", "fácil", "serrano", "duro", "rellena", "cherry", "caramelizada", "salpicón", "salsa", "jamon", "verde", "york",
                  "chino", "dulce", 'entero', 'japonesa', "lentejas", "limon", "manita", "refrescante", 'rápido', 'salteado','tortita', 'tomates', 'horno']
#platos = ["bocadillo", "estofado", "crema", "sándwich", "guiso", "helado", "lasaña", "pizza", "revuelto","risotto", "sopa", 'empanada', 'empanadilla', 'ensalada', 'tortilla', 'tarta',
          'potaje', ]

for nombre in lista:
   for palabra in nombre:
      palabra = palabra.lower()
      #if palabra.endswith(final):
      #    palabra = palabra.rstrip(palabra[-1])
       if palabra not in palabrasVacias: 
          ingredientes.add(palabra)
      if palabra in platos:
          ingredientes.remove(palabra)

ingredientes = list(ingredientes)
print(ingredientes)

['curry', 'lenteja', 'rúcula', 'aguacate', 'fresa', 'almeja', 'haba', 'alcachofa', 'pistacho', 'brócoli', 'huevo', 'garbanzo', 'calabaza', 'jamón', 'bacalao', 'paella', 'arándano', 'chocolate', 'almendra', 'gamba', 'seta', 'pimiento', 'atún', 'coliflor', 'nueces', 'repollo', 'arroz', 'chorizo', 'camarones', 'verdura', 'bacon', 'avellana', 'limón', 'pulpo', 'ajo', 'espaguetis', 'merluza', 'calamares', 'mostaza', 'piña', 'cebolla', 'pechuga', 'panceta', 'champiñones', 'conejo', 'ciruela', 'zanahoria', 'patata', 'pollo', 'queso', 'pavo', 'cerdo', 'apio', 'naranja', 'tomate', 'acelga', 'ternera', 'alubia', 'castaña', 'yogur', 'solomillo', 'pepino', 'espinaca', 'tocino', 'leche', 'espárrago']

# **Carga y limpieza de dataset de precios por supermercado**

In [ ]:
carrefour = pd.read_csv("/content/datamarket_productos_de_supermercados_2022_11_carrefour.csv", 
                        usecols=["url","supermarket","name","price","reference_price","reference_unit", "insert_date"])
carrefour = carrefour.convert_dtypes()
carrefour.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46909 entries, 0 to 46908
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              46909 non-null  string
 1   supermarket      46909 non-null  string
 2   name             46878 non-null  string
 3   price            46909 non-null  Float64
 4   reference_price  46909 non-null  Float64
 5   reference_unit   46909 non-null  string
 6   insert_date      46909 non-null  string
dtypes: Float64(2), string(5)
memory usage: 2.6 MB

In [ ]:
carrefour = carrefour.drop(carrefour[carrefour["name"].isna()].index) 
carrefour.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46878 entries, 0 to 46908
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              46878 non-null  string
 1   supermarket      46878 non-null  string
 2   name             46878 non-null  string
 3   price            46878 non-null  Float64
 4   reference_price  46878 non-null  Float64
 5   reference_unit   46878 non-null  string
 6   insert_date      46878 non-null  string
dtypes: Float64(2), string(5)
memory usage: 3.0 MB

In [ ]:
carrefour["insert_date"].unique()

<StringArray>
['2022-11-01', '2022-11-02', '2022-11-03', '2022-11-04', '2022-11-05',
 '2022-11-06', '2022-11-07', '2022-11-08', '2022-11-09', '2022-11-10',
 '2022-11-11', '2022-11-12', '2022-11-13', '2022-11-14', '2022-11-15',
 '2022-11-16', '2022-11-17']
Length: 17, dtype: string

In [ ]:
carrefour = carrefour[carrefour["insert_date"]==("2022-11-17")]
carrefour.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2910 entries, 43998 to 46908
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              2910 non-null   string
 1   supermarket      2910 non-null   string
 2   name             2910 non-null   string
 3   price            2910 non-null   Float64
 4   reference_price  2910 non-null   Float64
 5   reference_unit   2910 non-null   string
 6   insert_date      2910 non-null   string
dtypes: Float64(2), string(5)
memory usage: 187.6 KB

In [ ]:
carrefour_lista = list(carrefour["name"])
carrefour_seleccion = pd.DataFrame(columns=carrefour.columns)

for i in range(len(ingredientes)):
  for j in range(len(carrefour_lista)):
    if ingredientes[i] in carrefour_lista[j]:
        carrefour_seleccion = carrefour_seleccion.append(carrefour.iloc[j])

carrefour_seleccion.info()
carrefour_seleccion.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 475 entries, 44626 to 46907
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              475 non-null    object
 1   supermarket      475 non-null    object
 2   name             475 non-null    object
 3   price            475 non-null    float64
 4   reference_price  475 non-null    float64
 5   reference_unit   475 non-null    object
 6   insert_date      475 non-null    object
dtypes: float64(2), object(5)
memory usage: 29.7+ KB

,url,supermarket,name,price,reference_price,reference_unit,insert_date
44626,https://www.carrefour.es/supermercado/wok-de-t...,carrefour-es,Wok de tallarines con pollo al curry Carrefour...,3.25,3.25,ud,2022-11-17
46169,https://www.carrefour.es/supermercado/toallita...,carrefour-es,Toallitas limpiadoras con aguacate bio Mustela...,11.99,0.07,ud,2022-11-17
44006,https://www.carrefour.es/supermercado/gel-de-d...,carrefour-es,Gel de ducha fresa y nata Tulipán Negro 650 ml.,1.56,0.24,100ml,2022-11-17
44088,https://www.carrefour.es/supermercado/enjuague...,carrefour-es,Enjuague bucal infantil fresh sabor fresa Carr...,1.50,0.30,100ml,2022-11-17
44152,https://www.carrefour.es/supermercado/lubrican...,carrefour-es,Lubricante sabor y aroma fresa Durex 50 ml.,10.55,21.10,100ml,2022-11-17

In [ ]:
dia = pd.read_csv("/content/datamarket_productos_de_supermercados_2022_11_dia.csv", 
                        usecols=["url","supermarket","name","price","reference_price","reference_unit", "insert_date"])
dia = dia.convert_dtypes()
dia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90777 entries, 0 to 90776
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              90777 non-null  string
 1   supermarket      90777 non-null  string
 2   name             90777 non-null  string
 3   price            90777 non-null  Float64
 4   reference_price  90777 non-null  Float64
 5   reference_unit   90777 non-null  string
 6   insert_date      90777 non-null  string
dtypes: Float64(2), string(5)
memory usage: 5.0 MB

In [ ]:
dia = dia[dia["insert_date"]==("2022-11-17")]

dia_lista = list(dia["name"])
dia_seleccion = pd.DataFrame(columns=dia.columns)

for i in range(len(ingredientes)):
  for j in range(len(dia_lista)):
    if ingredientes[i] in dia_lista[j]:
        dia_seleccion = dia_seleccion.append(dia.iloc[j])

dia_seleccion.info()
dia_seleccion.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1937 entries, 86922 to 90703
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              1937 non-null   object
 1   supermarket      1937 non-null   object
 2   name             1937 non-null   object
 3   price            1937 non-null   float64
 4   reference_price  1937 non-null   float64
 5   reference_unit   1937 non-null   object
 6   insert_date      1937 non-null   object
dtypes: float64(2), object(5)
memory usage: 121.1+ KB

,url,supermarket,name,price,reference_price,reference_unit,insert_date
86922,https://www.dia.es/compra-online/despensa/coci...,dia-es,MAGGI fideos fusian India curry sobre 118 gr,1.69,14.32,kg,2022-11-17
88362,https://www.dia.es/compra-online/despensa/sal-...,dia-es,DIA VEGECAMPO curry en polvo bote 42 gr,0.85,20.24,kg,2022-11-17
86447,https://www.dia.es/compra-online/platos-prepar...,dia-es,DIA AL PUNTO lentejas con chorizo lata 430 gr,1.05,2.53,kg,2022-11-17
86450,https://www.dia.es/compra-online/platos-prepar...,dia-es,DIA AL PUNTO lentejas con verduras lata 415 gr,1.05,2.53,kg,2022-11-17
86451,https://www.dia.es/compra-online/platos-prepar...,dia-es,LITORAL lentejas a la riojana lata 430 gr,1.99,4.63,kg,2022-11-17

In [ ]:
mercadona = pd.read_csv("/content/datamarket_productos_de_supermercados_2022_11_mercadona.csv",
                        usecols=["url","supermarket","name","price","reference_price","reference_unit", "insert_date"])
mercadona = mercadona.convert_dtypes()
mercadona.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90947 entries, 0 to 90946
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              90947 non-null  string
 1   supermarket      90947 non-null  string
 2   name             90947 non-null  string
 3   price            90947 non-null  Float64
 4   reference_price  90947 non-null  Float64
 5   reference_unit   90947 non-null  string
 6   insert_date      90947 non-null  string
dtypes: Float64(2), string(5)
memory usage: 5.0 MB

In [ ]:
mercadona = mercadona[mercadona["insert_date"]==("2022-11-17")]

mercadona_lista = list(mercadona["name"])
mercadona_seleccion = pd.DataFrame(columns=mercadona.columns)

for i in range(len(ingredientes)):
  for j in range(len(mercadona_lista)):
    if ingredientes[i] in mercadona_lista[j]:
        mercadona_seleccion = mercadona_seleccion.append(mercadona.iloc[j])

mercadona_seleccion.info()
mercadona_seleccion.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1338 entries, 86219 to 90184
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              1338 non-null   object
 1   supermarket      1338 non-null   object
 2   name             1338 non-null   object
 3   price            1338 non-null   float64
 4   reference_price  1338 non-null   float64
 5   reference_unit   1338 non-null   object
 6   insert_date      1338 non-null   object
dtypes: float64(2), object(5)
memory usage: 83.6+ KB

,url,supermarket,name,price,reference_price,reference_unit,insert_date
86219,https://tienda.mercadona.es/product/23623/croq...,mercadona-es,Croquetas Caprichos Thai Hacendado de coliflor...,3.00,13.334,kg,2022-11-17
87368,https://tienda.mercadona.es/product/4498/pollo...,mercadona-es,Pollo al curry Hacendado con arroz basmati,2.85,10.179,kg,2022-11-17
88586,https://tienda.mercadona.es/product/82961/salm...,mercadona-es,Salmón al curry Hacendado,5.50,16.924,kg,2022-11-17
88587,https://tienda.mercadona.es/product/83346/salm...,mercadona-es,Salmón al curry con arroz,3.50,12.728,kg,2022-11-17
87439,https://tienda.mercadona.es/product/33636/snac...,mercadona-es,Snacks de lenteja sabor queso y especias Snatt's,1.35,15.000,kg,2022-11-17

In [ ]:
precios_supermercados = pd.DataFrame()
precios_supermercados = precios_supermercados.append([carrefour_seleccion, dia_seleccion, mercadona_seleccion])
precios_supermercados.info()
precios_supermercados.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3750 entries, 44626 to 90184
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              3750 non-null   object
 1   supermarket      3750 non-null   object
 2   name             3750 non-null   object
 3   price            3750 non-null   float64
 4   reference_price  3750 non-null   float64
 5   reference_unit   3750 non-null   object
 6   insert_date      3750 non-null   object
dtypes: float64(2), object(5)
memory usage: 234.4+ KB

,url,supermarket,name,price,reference_price,reference_unit,insert_date
44626,https://www.carrefour.es/supermercado/wok-de-t...,carrefour-es,Wok de tallarines con pollo al curry Carrefour...,3.25,3.25,ud,2022-11-17
46169,https://www.carrefour.es/supermercado/toallita...,carrefour-es,Toallitas limpiadoras con aguacate bio Mustela...,11.99,0.07,ud,2022-11-17
44006,https://www.carrefour.es/supermercado/gel-de-d...,carrefour-es,Gel de ducha fresa y nata Tulipán Negro 650 ml.,1.56,0.24,100ml,2022-11-17
44088,https://www.carrefour.es/supermercado/enjuague...,carrefour-es,Enjuague bucal infantil fresh sabor fresa Carr...,1.50,0.30,100ml,2022-11-17
44152,https://www.carrefour.es/supermercado/lubrican...,carrefour-es,Lubricante sabor y aroma fresa Durex 50 ml.,10.55,21.10,100ml,2022-11-17

In [ ]:
resultado = pd.DataFrame()
for i in range(len(precios_supermercados)):
  if "rúcula" in list(precios_supermercados["name"])[i]:
    resultado = resultado.append(precios_supermercados.iloc[i])

resultado

NameError: ignored